namespace SudokuApp.ViewModels
{
    public class TranslateViewModels : BaseViewModel
    {
        //<string, string, string>; <język, nazwa_pola, translate>
        // Pole przechowujące domyślny język
        private string defaultLanguage;
        private TranslationManager translationManager;

        public TranslateViewModels()
        {
            defaultLanguage = Preferences.Default.Get("CurrentLanguage", "polski");
            translationManager = new TranslationManager();  
        }

        public string TranslatedText
        {
            get
            {
                // Tutaj wywołaj odpowiednią metodę z TranslationManager do tłumaczenia tekstu
                return translationManager.Translate(defaultLanguage, "ContinueLabel"); // Przykładowy tekst do tłumaczenia
            }
        }

        public void SetLanguage(string language)
        {
            // Ustawienie nowego języka w preferencjach
            Preferences.Set("ChosenLanguage", language);

            // Aktualizacja domyślnego języka
            defaultLanguage = language;

            // Tutaj możesz dodać dodatkową logikę, na przykład odświeżenie interfejsu użytkownika,
            // aby odzwierciedlić zmiany języka
        }
    }

    public class TranslationManager : BindableObject
    {
        // Domyślny język
        private string DefaultLanguage;

        // Słownik tłumaczeń
        private Dictionary<string, Dictionary<string, string>> translations;

        public TranslationManager()
        {
            DefaultLanguage = Preferences.Default.Get("CurrentLanguage", "polski");
            // Inicjalizacja słownika tłumaczeń
            translations = [];
            switch ( DefaultLanguage )
            {
                case "polski": AddTranslations("polski", new Dictionary<string, string>
                {
                    {"LabelContinue", "Kontunuuj grę"},
                    {"LabelNewGame", "Nowa gra"},
                    {"LabelLevel1", "Łatwy"},
                    {"LabelLevel2", "Średni"},
                    {"LabelLevel3", "Trudny"},
                    {"LabelLevel4", "Ekspert"},
                    {"LabelRestart", "Uruchom ponownie"},
                    {"LabelCancel", "Anuluj"},
                    {"LabelSettings", "USTAWIENIA"},
                    {"LabelDarkMode", "Tryb nocny"},
                    {"LabelSounds", "Efekty dźwiękowe"},
                    {"LabelVibrations", "Wibracje"},
                    {"LabelTimer", "Licznik"},
                    {"LabelMistakes", "Limit błędów"},
                    {"LabelAreas", "Wyróżnij obszary"},
                    {"LabelIdenticalNumber", "Wyróżnij identyczne cyfry"},
                    {"BtnTextRules", "ZASADY GRY"},
                    {"BtnTextLanguage", "ZMIEŃ JĘZYK"},
                    {"BtnDiscard", "Pomiń"},
                    {"LabelTouchCell", "Dotknij tę komórkę"},
                    {"LabelChooseNumber", "Wybierz tę cyfrę"},
                    {"LabelAddNumber", "W to pole można wstawić cyfrę"},
                    {"LabelFinal", "Udało Ci się wypełnić kwadrat, wiersz i kolumnę. Celem Sudoku jest wstawienie w każdym kwadracie, wierszu i kolumnie cyfry od 1 do 9."},
                    {"BtnFinal", "Dotknij aby kontynuować"},
                    {"LabelGetTips", "Uzyskaj wskazówki"},
                    {"LabelSeeTips", "Zobacz reklamę aby uzyskać dodatkową wskazówkę."},
                    {"BtnSeeAd", "Obejrzyj Reklamę"},
                    {"LabelMistake", "Błąd" },
                    {"DisplayAlertFinalText", "Udało Ci się prawidłowo rozwiązać Sudoku."},
                    {"LabelNotesOn", "Wł."},
                    {"LabelNotesOff", "Wył."},
                    {"AdTitleText", "Reklama!"},
                    {"AdBodyText", "Obejrzyj reklamę aby dalej grać."},
                    {"TextYes", "Tak"},
                    {"TextNo", "Nie"},
                    {"LabelBack", "Cofnij"},
                    {"LabelErase", "Wyczyść"},
                    {"LabelNotes", "Notatki"},
                    {"LabelHint", "Pomoc"},
                    {"LabelLaunguageText", "ZMIEŃ JĘZYK"},
                    {"LabelLaunguageConfirm", "POTWIERDŹ"},
                    {"GetHint", "Free x "},
                    {"BtnTextStatistic", "STATYSTYKI"},
                    {"LabelGS", "Rozpoczęte gry:"},
                    {"LabelGW", "Wygrane gry:"},
                    {"LabelWR", "Stosunek wygranych:"},
                    {"LabelWWM", "Wygrane bez pomyłek:"},
                    {"LabelBT", "Najlepszy czas:"},
                    {"LabelAT", "Średni czas:"},
                    {"LabelCWS", "Obecna seria wygranych:"},
                    {"LabelBWS", "Najdłuższa seria wygranych:"},
                    {"BtnReset", "Wyzeruj statystyki"},
                    {"ResetStatisticsText", "Statystyki dla tego poziomu trudności () zostaną usunięte. Czy chcesz kontynuować?"},
                }); break;
                case "english": AddTranslations("english", new Dictionary<string, string>
                {
                    {"LabelContinue", "Continue game"},
                    {"LabelNewGame", "New Game"},
                    {"LabelLevel1", "Easy"},
                    {"LabelLevel2", "Medium"},
                    {"LabelLevel3", "Hard"},
                    {"LabelLevel4", "Expert"},
                    {"LabelRestart", "Restart"},
                    {"LabelCancel", "Cancel"},
                    {"LabelSettings", "SETTINGS"},
                    {"LabelDarkMode", "Dark Mode"},
                    {"LabelSounds", "Sounds Effect"},
                    {"LabelVibrations", "Vibrations"},
                    {"LabelTimer", "Timer"},
                    {"LabelMistakes", "Mistake Limit"},
                    {"LabelAreas", "Highlight Areas"},
                    {"LabelIdenticalNumber", "Highlight Identical Numbers"},
                    {"BtnTextRules", "HOW TO PLAY"},
                    {"BtnTextLanguage", "CHANGE LANGUAGE"},
                    {"BtnDiscard", "Skip"},
                    {"LabelTouchCell", "Tap this cell"},
                    {"LabelChooseNumber", "Select this number"},
                    {"LabelAddNumber", "This cell can be filled with the number"},
                    {"LabelFinal", "You already filled a square, row and column. The goal in Sudoku is to make sure every square, row and column contains the numbers 1-9."},
                    {"BtnFinal", "Tap to proceed"},
                    {"LabelGetTips", "Get tips"},
                    {"LabelSeeTips", "Watch the ad for an additional tip."},
                    {"BtnSeeAd", "Watch the Advertisement"},
                    {"LabelMistake", "Mistake" },
                    {"DisplayAlertFinalText", "You successfully solved Sudoku."},
                    {"LabelNotesOn", "On"},
                    {"LabelNotesOff", "Off"},
                    {"AdTitleText", "Advertisement!"},
                    {"AdBodyText", "Watch the ad to continue playing"},
                    {"TextYes", "Yes"},
                    {"TextNo", "No"},
                    {"LabelBack", "Undo"},
                    {"LabelErase", "Erase"},
                    {"LabelNotes", "Notes"},
                    {"LabelHint", "Hint"},
                    {"LabelLaunguageConfirm", "CONFIRM"},
                    {"GetHint", "Free x "},
                    {"BtnTextStatistic", "STATISTICS"},
                    {"LabelGS", "Games started:"},
                    {"LabelGW", "Games won:"},
                    {"LabelWR", "Win rate:"},
                    {"LabelWWM", "Wins without mistakes:"},
                    {"LabelBT", "Best time:"},
                    {"LabelAT", "Average time:"},
                    {"LabelCWS", "Current wins streak:"},
                    {"LabelBWS", "Best win streak:"},
                    {"BtnReset", "Reset statistics"},
                    {"ResetStatisticsText", "statistics will be lost. Are you sure?"},
                }); break;
                case "cesky": AddTranslations("cesky", new Dictionary<string, string>
                {//a b c č d ď e é ě f g h ch i í j k l m n ň o p q r ř s š t ť u ú ů v w x y ý z ž
                 //A B C Č D Ď E É Ě F G H CH I Í J K L M N Ň O P Q R Ř S Š T Ť U Ú Ů V W X Y Ý Z Ž
                    {"LabelContinue", "Pokračovat ve hře"},
                    {"LabelNewGame", "Nová hra"},
                    {"LabelLevel1", "Snadná"},
                    {"LabelLevel2", "Střední"},
                    {"LabelLevel3", "Těžká"},
                    {"LabelLevel4", "Expert"},
                    {"LabelRestart", "Restartujte"},
                    {"LabelCancel", "Zrusit"},
                    {"LabelSettings", "NASTAVENÍ"},
                    {"LabelDarkMode", "Tmavý mód"},
                    {"LabelSounds", "Zvukové efekty"},
                    {"LabelVibrations", "Vibrace"},
                    {"LabelTimer", "Čas"},
                    {"LabelMistakes", "Limit chyb"},
                    {"LabelAreas", "Zvýraznit oblasti"},
                    {"LabelIdenticalNumber", "Zvýraznit stejná čísla"},
                    {"BtnTextRules", "JAK HRÁT"},
                    {"BtnTextLanguage", "ZMĚNIT JAZYK"},
                    {"BtnDiscard", "Přeskočit"},
                    {"LabelTouchCell", "Klepni na tuto buňku"},
                    {"LabelChooseNumber", "Vyber toto číslo"},
                    {"LabelAddNumber", "Do této buňky lze doplnit číslo"},
                    {"LabelFinal", "Už jste vyplnili čtverec, řádek a sloupec. Cílem v Sudoku je zajistit, aby každý čtverec, řádek a sloupec obsahoval čísla 1-9."},
                    {"BtnFinal", "Klepni pro pokračováni"},
                    {"LabelGetTips", "Získejte tipy"},
                    {"LabelSeeTips", "Podívejte se na inzerát, kde najdete další tip."},
                    {"BtnSeeAd", "Podívejte se na inzerát"},
                    {"LabelMistake", "Chyby" },
                    {"DisplayAlertFinalText", "Úspěšně jste vyřešili sudoku."},
                    {"LabelNotesOn", "Zap."},
                    {"LabelNotesOff", "Vyp."},
                    {"AdTitleText", "Advertisement!"},
                    {"AdBodyText", "Chcete-li pokračovat ve hře, sledujte reklamu"},
                    {"TextYes", "Ano"},
                    {"TextNo", "Ne"},
                    {"LabelBack", "Zpět"},
                    {"LabelErase", "Smazat"},
                    {"LabelNotes", "Pozn."},
                    {"LabelHint", "Rada"},
                    {"LabelLaunguageConfirm", "POTVRDIT"},
                    {"GetHint", "Free x "},
                    {"BtnTextStatistic", "STATISTIKY"},
                    {"LabelGS", "Zahájeno her:"},
                    {"LabelGW", "Vyhráno her:"},
                    {"LabelWR", "Procento výher:"},
                    {"LabelWWM", "Výher bez chyb:"},
                    {"LabelBT", "Nejlepší čas:"},
                    {"LabelAT", "Průměrný čas:"},
                    {"LabelCWS", "Aktuální série výher:"},
                    {"LabelBWS", "Nejlepší série výher:"},
                    {"BtnReset", "Obnovit statistiky"},
                    {"ResetStatisticsText", "Statistiky pro obtížnost () budou ztraceny. Viš to jistě?"},
                }); break;
                case "dansk": AddTranslations("dansk", new Dictionary<string, string>
                {
                    //a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, æ, ø, å.
                    //A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, Æ, Ø, Å.
                    {"LabelContinue", "Fortsæt spil"},
                    {"LabelNewGame", "Nyt spil"},
                    {"LabelLevel1", "Nemt"},
                    {"LabelLevel2", "Medium"},
                    {"LabelLevel3", "Svært"},
                    {"LabelLevel4", "Expert"},
                    {"LabelRestart", "Genstart"},
                    {"LabelCancel", "Annuller"},
                    {"LabelSettings", "INDSTILLINGER"},
                    {"LabelDarkMode", "Mørk tema"},
                    {"LabelSounds", "Lydeeffekt"},
                    {"LabelVibrations", "Vibrationer"},
                    {"LabelTimer", "Timer"},
                    {"LabelMistakes", "Fejlgrænse"},
                    {"LabelAreas", "Fremhæv områder"},
                    {"LabelIdenticalNumber", "Fremhæv identiske tal"},
                    {"BtnTextRules", "SÅDAN SPILLER DU"},
                    {"BtnTextLanguage", "SKIFT SPROG"},
                    {"BtnDiscard", "Spring over"},
                    {"LabelTouchCell", "Tryk på cellen"},
                    {"LabelChooseNumber", "Vælg dette tal"},
                    {"LabelAddNumber", "Denne celle kan udfyldes med tallet"},
                    {"LabelFinal", "Du har allerede udfyldt et kvadrat, en række og en kolonne. Målet i Sudoku er at sørge, at alle felter, rækker og kolonner indeholder tallene 1-9."},
                    {"BtnFinal", "Tryk for at fortsætte"},
                    {"LabelGetTips", "Få tips"},
                    {"LabelSeeTips", "Se annoncen for et ekstra tip."},
                    {"BtnSeeAd", "Se annoncen"},
                    {"LabelMistake", "Fejl" },
                    {"DisplayAlertFinalText", "Du løste Sudoku med succes."},
                    {"LabelNotesOn", "På"},
                    {"LabelNotesOff", "Af"},
                    {"AdTitleText", "Reklame!"},
                    {"AdBodyText", "Se annoncen for at fortsætte med at spille"},
                    {"TextYes", "Ja"},
                    {"TextNo", "Nej"},
                    {"LabelBack", "Fortryd"},
                    {"LabelErase", "Slet"},
                    {"LabelNotes", "Noter"},
                    {"LabelHint", "Tip"},
                    {"LabelLaunguageConfirm", "BEKRÆFTE"},
                    {"GetHint", "Free x "},
                    { "BtnTextStatistic", "STATISTIK"},
                    {"LabelGS", "Spil begyndt:"},
                    {"LabelGW", "Spil vundet:"},
                    {"LabelWR", "Succesprocent:"},
                    {"LabelWWM", "Spil uden fejl:"},
                    {"LabelBT", "Hurtigste tid:"},
                    {"LabelAT", "Gennemsnitstid:"},
                    {"LabelCWS", "Sejrsstime:"},
                    {"LabelBWS", "Bedste sejrsstime:"},
                    {"BtnReset", "Nulstil statistikker"},
                    {"ResetStatisticsText", "statistikker vil gå tabt. Er du sikker?"},
                }); break;
                case "deutsch": AddTranslations("deutsch", new Dictionary<string, string>
                {
                    //a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, ä, ö, ü, ß.
                    //A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, Ä, Ö, Ü, ß.
                    {"LabelContinue", "Spiel fortsetzen"},
                    {"LabelNewGame", "Neues Spiel"},
                    {"LabelLevel1", "Leicht"},
                    {"LabelLevel2", "Mittel"},
                    {"LabelLevel3", "Schwer"},
                    {"LabelLevel4", "Experte"},
                    {"LabelRestart", "Neustart"},
                    {"LabelCancel", "Abbrechen"},
                    {"LabelSettings", "EINSTELLUNGEN"},
                    {"LabelDarkMode", "Dunkler Modus"},
                    {"LabelSounds", "Sound-Effekte"},
                    {"LabelVibrations", "Vibration"},
                    {"LabelTimer", "Timer"},
                    {"LabelMistakes", "Fehler-Limit"},
                    {"LabelAreas", "Bereiche Markieren"},
                    {"LabelIdenticalNumber", "Markiere identische Zahlen"},
                    {"BtnTextRules", "WIE MAN SPIELT"},
                    {"BtnTextLanguage", "SPRACHE ÄNDERN"},
                    {"BtnDiscard", "Überspringen"},
                    {"LabelTouchCell", "Klick auf diesem Feld"},
                    {"LabelChooseNumber", "Wähle diese Zahl"},
                    {"LabelAddNumber", "Dieses Feld kann mit der Zahl 2 gefüllt werden"},
                    {"LabelFinal", "Sie haben bereits ein Quadrat, eine Zeile und eine Spalte gefüllt. Das Ziel bei Sudoku besteht darin, sicherzustellen, dass jedes Quadrat, jede Zeile und jede Spalte die Zahlen 1–9 enthält."},
                    {"BtnFinal", "Klicken zum Fortfahren"},
                    {"LabelGetTips", "Holen Tipps"},
                    {"LabelSeeTips", "Sehen Sie sich die Anzeige an, um einen zusätzlichen Tipp zu erhalten."},
                    {"BtnSeeAd", "Sehen die Werbung an"},
                    {"LabelMistake", "Fehler" },
                    {"DisplayAlertFinalText", "Du hast Sudoku erfolgreich gelöst."},
                    {"LabelNotesOn", "An"},
                    {"LabelNotesOff", "Aus"},
                    {"AdTitleText", "Werbung!"},
                    {"AdBodyText", "Sehen die Anzeige an, um weiterzuspielen"},
                    {"TextYes", "Ja"},
                    {"TextNo", "Nein"},
                    {"LabelBack", "Zurück"},
                    {"LabelErase", "Löschen"},
                    {"LabelNotes", "Notizen"},
                    {"LabelHint", "Tipp"},
                    {"LabelLaunguageConfirm", "BESTÄTIGEN"},
                    {"GetHint", "Free x "},
                    { "BtnTextStatistic", "STATISTIKEN"},
                    {"LabelGS", "Spiele gestarted:"},
                    {"LabelGW", "Spiele gewonnen:"},
                    {"LabelWR", "Gewinnrate:"},
                    {"LabelWWM", "Siege ohne Fehler:"},
                    {"LabelBT", "Beste Zeit:"},
                    {"LabelAT", "Durchschnittlicze Zeit:"},
                    {"LabelCWS", "Aktuelle Gewinnserie:"},
                    {"LabelBWS", "Beste Gewinnserie:"},
                    {"BtnReset", "Statistiken zurücksetzen"},
                    {"ResetStatisticsText", "-Statistiken gehen verloren. Bist du sicher?"},
                }); break;
                case "espanol": AddTranslations("espanol", new Dictionary<string, string>
                {
                            //a, b, c, d, e, f, g, h, i, j, k, l, m, n, ñ, o, p, q, r, s, t, u, v, w, x, y, z
                            //A, B, C, D, E, F, G, H, I, J, K, L, M, N, Ñ, O, P, Q, R, S, T, U, V, W, X, Y, Z.
                    {"LabelContinue", "Continuar partida"},
                    {"LabelNewGame", "Nueva partida"},
                    {"LabelLevel1", "Fácil"},
                    {"LabelLevel2", "Intermedio"},
                    {"LabelLevel3", "Dificil"},
                    {"LabelLevel4", "Experto"},
                    {"LabelRestart", "Reiniciar"},
                    {"LabelCancel", "Cancelar"},
                    {"LabelSettings", "CONFIGURACIÓN"},
                    {"LabelDarkMode", "Modo oscuro"},
                    {"LabelSounds", "Efectos de sonido"},
                    {"LabelVibrations", "Vibraciones"},
                    {"LabelTimer", "Contador"},
                    {"LabelMistakes", "Límite de errores"},
                    {"LabelAreas", "Áreas destacadas"},
                    {"LabelIdenticalNumber", "Resaltar números idénticos"},
                    {"BtnTextRules", "CÓMO JUGAR"},
                    {"BtnTextLanguage", "CAMBIAR IDIOMA"},
                    {"BtnDiscard", "Saltar"},
                    {"LabelTouchCell", "Pulsa esta celda"},
                    {"LabelChooseNumber", "Selecciona este número"},
                    {"LabelAddNumber", "Esta celda puede llenarse con el número"},
                    {"LabelFinal", "Ya llenaste un cuadrado, fila y columna. El objetivo del Sudoku es asegurarse de que cada cuadrado, fila y columna contenga los números del 1 al 9."},
                    {"BtnFinal", "Pulsa para continuar"},
                    {"LabelGetTips", "Obtener consejos"},
                    {"LabelSeeTips", "Mire el anuncio para obtener un consejo adicional."},
                    {"BtnSeeAd", "Mira el anuncio"},
                    {"LabelMistake", "Errores" },
                    {"DisplayAlertFinalText", "Resolviste con éxito el Sudoku."},
                    {"LabelNotesOn", "On"},
                    {"LabelNotesOff", "Off"},
                    {"AdTitleText", "Anuncio!"},
                    {"AdBodyText", "Mira el anuncio para seguir jugando."},
                    {"TextYes", "Sí"},
                    {"TextNo", "No"},
                    {"LabelBack", "Anular"},
                    {"LabelErase", "Borrar"},
                    {"LabelNotes", "Notas"},
                    {"LabelHint", "Pista"},
                    {"LabelLaunguageConfirm", "CONFIRMAR"},
                    {"GetHint", "Free x "},
                    { "BtnTextStatistic", "ESTADÍSTICAS"},
                    {"LabelGS", "Partidas jugadas:"},
                    {"LabelGW", "Partidas ganadas:"},
                    {"LabelWR", "Procentaje de victorias:"},
                    {"LabelWWM", "Victorias sin errores:"},
                    {"LabelBT", "Mejor tiempo:"},
                    {"LabelAT", "Tiempo medio:"},
                    {"LabelCWS", "Racha actual:"},
                    {"LabelBWS", "Mejor racha:"},
                    {"BtnReset", "Reiniciar estadísticas"},
                    {"ResetStatisticsText", "Las estadísticas del nivel () se perderán. Estás seguro?"},
                }); break;
                case "francais": AddTranslations("francais", new Dictionary<string, string>
                {//é, è, ê, ë, à, â, î, ï, ô, û, ü, ç   É, È, Ê, Ë, À, Â, Î, Ï, Ô, Û, Ü, Ç
                    {"LabelContinue", "Reprendre la partie"},
                    {"LabelNewGame", "Nouvelle Partie"},
                    {"LabelLevel1", "Facily"},
                    {"LabelLevel2", "Moyen"},
                    {"LabelLevel3", "Difficile"},
                    {"LabelLevel4", "Expert"},
                    {"LabelRestart", "Recommencer"},
                    {"LabelCancel", "Annuler"},
                    {"LabelSettings", "PARAMÈTRES"},
                    {"LabelDarkMode", "Mode Sombre"},
                    {"LabelSounds", "Effets Sonores"},
                    {"LabelVibrations", "Vibrations"},
                    {"LabelTimer", "Timer"},
                    {"LabelMistakes", "Limite d'erreur"},
                    {"LabelAreas", "Zones en Surbrillance"},
                    {"LabelIdenticalNumber", "Mettre les Chiffres Identiques en Surbrillance"},
                    {"BtnTextRules", "COMMENT JOUER"},
                    {"BtnTextLanguage", "CHANGER DE LANGUE"},
                    {"BtnDiscard", "Passer"},
                    {"LabelTouchCell", "Touchez cette cellule"},
                    {"LabelChooseNumber", "Sélectionnez ce chiffre"},
                    {"LabelAddNumber", "Cette cellule peut être remplie avec le chiffre"},
                    {"LabelFinal", "Vous avez déjà rempli un carré, une ligne et une colonne. Le but du Sudoku est de s'assurer que chaque carré, ligne et colonne contient les chiffres 1 à 9."},
                    {"BtnFinal", "Touchez pour continuer"},
                    {"LabelGetTips", "Obtenez des conseils"},
                    {"LabelSeeTips", "Regardez l'annonce pour un conseil supplémentaire."},
                    {"BtnSeeAd", "Regardez la publicité"},
                    {"LabelMistake", "Erreurs" },
                    {"DisplayAlertFinalText", "Vous avez résolu le Sudoku avec succès."},
                    {"LabelNotesOn", "Sur"},
                    {"LabelNotesOff", "Dés."},
                    {"AdTitleText", "Publicité!"},
                    {"AdBodyText", "Regardez la publicité pour continuer à jouer"},
                    {"TextYes", "Oui"},
                    {"TextNo", "Non"},
                    {"LabelBack", "Annuler"},
                    {"LabelErase", "Effacer"},
                    {"LabelNotes", "Notes"},
                    {"LabelHint", "Indices"},
                    {"LabelLaunguageConfirm", "CONFIRMER"},
                    {"GetHint", "Free x "},
                    { "BtnTextStatistic", "STATISTIQUES"},
                    {"LabelGS", "Parties commencées:"},
                    {"LabelGW", "Parties gagnées:"},
                    {"LabelWR", "Ratio de victoire:"},
                    {"LabelWWM", "Victoires sans erreur:"},
                    {"LabelBT", "Meilleur temps:"},
                    {"LabelAT", "Temps moyen:"},
                    {"LabelCWS", "Série de victoires actuelle:"},
                    {"LabelBWS", "Meilleure série de victoires:"},
                    {"BtnReset", "Réinitialiser les statistiques"},
                    {"ResetStatisticsText", "Les statistiques () seront perdues. Êtes-vous sûr de vouloir continuer?"},
                }); break;
                case "italiano": AddTranslations("italiano", new Dictionary<string, string>
                {
                    {"LabelContinue", "Continua partita"},
                    {"LabelNewGame", "Nuova Partita"},
                    {"LabelLevel1", "Facile"},
                    {"LabelLevel2", "Intermedio"},
                    {"LabelLevel3", "Difficile"},
                    {"LabelLevel4", "Esperto"},
                    {"LabelRestart", "Ricomincia"},
                    {"LabelCancel", "Cancella"},
                    {"LabelSettings", "OPZIONI"},
                    {"LabelDarkMode", "Modalità scura"},
                    {"LabelSounds", "Effetti Sonori"},
                    {"LabelVibrations", "Vibrazioni"},
                    {"LabelTimer", "Timer"},
                    {"LabelMistakes", "Limite Errori"},
                    {"LabelAreas", "Evidenzia aree"},
                    {"LabelIdenticalNumber", "Evidenzia Numeri Identici"},
                    {"BtnTextRules", "COME SI GIOCA"},
                    {"BtnTextLanguage", "CAMBIA LINGUA"},
                    {"BtnDiscard", "Salta"},
                    {"LabelTouchCell", "Clicca su questa casella"},
                    {"LabelChooseNumber", "Scegli questo numero"},
                    {"LabelAddNumber", "In questa casella puoi inserire il numero"},
                    {"LabelFinal", "Hai già riempito un riquadro, una colonna e una riga. L'obiettivo del Sudoku è posizionare tutti i numeri da 1 a 9 in ogni riquardo, collona e riga."},
                    {"BtnFinal", "Clicca per procedere"},
                    {"LabelGetTips", "Ottieni suggerimenti"},
                    {"LabelSeeTips", "Guarda l'annuncio per un ulteriore suggerimento."},
                    {"BtnSeeAd", "Guarda la pubblicità"},
                    {"LabelMistake", "Errori" },
                    {"DisplayAlertFinalText", "Hai risolto con successo il Sudoku."},
                    {"LabelNotesOn", "On"},
                    {"LabelNotesOff", "Off"},
                    {"AdTitleText", "Pubblicità!"},
                    {"AdBodyText", "Guarda l'annuncio per continuare a giocare"},
                    {"TextYes", "Yes"},
                    {"TextNo", "No"},
                    {"LabelBack", "Annulla"},
                    {"LabelErase", "Cancella"},
                    {"LabelNotes", "Note"},
                    {"LabelHint", "Consiglio"},
                    {"LabelLaunguageConfirm", "CONFERMARE"},
                    {"GetHint", "Free x "},
                    { "BtnTextStatistic", "STATISTICHE"},
                    {"LabelGS", "Partitie iniziate:"},
                    {"LabelGW", "Partitie vinte:"},
                    {"LabelWR", "% vittoria:"},
                    {"LabelWWM", "Vittorie senza errori:"},
                    {"LabelBT", "Miglior tempo:"},
                    {"LabelAT", "Tempo medio:"},
                    {"LabelCWS", "Striscia positiva:"},
                    {"LabelBWS", "Miglior striscia:"},
                    {"BtnReset", "Reset statistiche"},
                    {"ResetStatisticsText", "Le statistiche per il livello () saranno perse. Sei sicuro?"},
                }); break;
                case "nederlands": AddTranslations("nederlands", new Dictionary<string, string>
                {
                    {"LabelContinue", "Spel voortzetten"},
                    {"LabelNewGame", "Nieuw spel"},
                    {"LabelLevel1", "Makkelijk"},
                    {"LabelLevel2", "Gemiddeld"},
                    {"LabelLevel3", "Moeilijk"},
                    {"LabelLevel4", "Expert"},
                    {"LabelRestart", "Opnieuw beginnen"},
                    {"LabelCancel", "Annuleer"},
                    {"LabelSettings", "INSTELLINGEN"},
                    {"LabelDarkMode", "Nachtmodus"},
                    {"LabelSounds", "Geluidseffecten"},
                    {"LabelVibrations", "Trillingen"},
                    {"LabelTimer", "Tijd"},
                    {"LabelMistakes", "Maximale aantal fouten"},
                    {"LabelAreas", "Markeer gebieden"},
                    {"LabelIdenticalNumber", "Markeer identieke cijfers"},
                    {"BtnTextRules", "HOE SPELEN JE SUDOKU"},
                    {"BtnTextLanguage", "TAAL WIJZIGEN"},
                    {"BtnDiscard", "Overslaan"},
                    {"LabelTouchCell", "Tik op deze cel"},
                    {"LabelChooseNumber", "Selecteer dit cijfer"},
                    {"LabelAddNumber", "Deze cel kan ingevuld worden met het cijfer"},
                    {"LabelFinal", "Je hebt reeds een block, rij en kolom voltooid. Het doel vin Sudoku is om voor te zorgen dat in elk blok, en elke rij en kolom de cijfers 1-9 bevatten."},
                    {"BtnFinal", "Tik om door te gaan"},
                    {"LabelGetTips", "Ontvang tips"},
                    {"LabelSeeTips", "Bekijk de advertentie voor een extra tip."},
                    {"BtnSeeAd", "Bekijk de advertentie"},
                    {"LabelMistake", "Fouten" },
                    {"DisplayAlertFinalText", "Je hebt Sudoku succesvol opgelost."},
                    {"LabelNotesOn", "Aan"},
                    {"LabelNotesOff", "Uit"},
                    {"AdTitleText", "Advertentie!"},
                    {"AdBodyText", "Bekijk de advertentie om verder te spelen"},
                    {"TextYes", "Ja"},
                    {"TextNo", "Nee"},
                    {"LabelBack", "Undo"},
                    {"LabelErase", "Wissen"},
                    {"LabelNotes", "Notities"},
                    {"LabelHint", "Hint"},
                    {"LabelLaunguageConfirm", "BEVESTIGEN"},
                    {"GetHint", "Free x "},
                    { "BtnTextStatistic", "STATISTIEKEN"},
                    {"LabelGS", "Spellen begonnen:"},
                    {"LabelGW", "Spellen gewonnen:"},
                    {"LabelWR", "Winratio:"},
                    {"LabelWWM", "Overwinningen zonder fouten:"},
                    {"LabelBT", "Beste tijd:"},
                    {"LabelAT", "Gemiddelde tijd:"},
                    {"LabelCWS", "Huidige winnende reeks:"},
                    {"LabelBWS", "Beste winnende reeks:"},
                    {"BtnReset", "Statistieken resetten"},
                    {"ResetStatisticsText", "De statistieken van het niveau () worden gereset. Weet je het zeker?"},
                }); break;
                case "norsk": AddTranslations("norsk", new Dictionary<string, string>
                {//æ, ø, å  Æ, Ø, Å
                    {"LabelContinue", "Fortsett spill"},
                    {"LabelNewGame", "Nyt spill"},
                    {"LabelLevel1", "Enkel"},
                    {"LabelLevel2", "Middels"},
                    {"LabelLevel3", "Vanskelig"},
                    {"LabelLevel4", "Ekspert"},
                    {"LabelRestart", "Restart"},
                    {"LabelCancel", "Avbryt"},
                    {"LabelSettings", "INNSTILLINGER"},
                    {"LabelDarkMode", "Mørk modus"},
                    {"LabelSounds", "Lydeffekter"},
                    {"LabelVibrations", "Vibreringer"},
                    {"LabelTimer", "Timer"},
                    {"LabelMistakes", "Grense for antall feil"},
                    {"LabelAreas", "Uthev områder"},
                    {"LabelIdenticalNumber", "Uthev like tall"},
                    {"BtnTextRules", "SPILLEREGLER"},
                    {"BtnTextLanguage", "ENDRE SPRÅK"},
                    {"BtnDiscard", "Hopp over"},
                    {"LabelTouchCell", "Trykk på denne ruten"},
                    {"LabelChooseNumber", "Velg dette tallet"},
                    {"LabelAddNumber", "I denne ruten kan du fylle inn tallet "},
                    {"LabelFinal", "Du har allerede fylt en blokk, rad og kolonne. Målet med Sudoku er å sørge for at hver blokk, rad og kolonne inneholder tallene 1-9."},
                    {"BtnFinal", "Trykk for å fortsette"},
                    {"LabelGetTips", "Få tips"},
                    {"LabelSeeTips", "Se annonsen for et ekstra tips."},
                    {"BtnSeeAd", "Se annonsen"},
                    {"LabelMistake", "Feil" },
                    {"DisplayAlertFinalText", "Du løste Sudoku."},
                    {"LabelNotesOn", "På"},
                    {"LabelNotesOff", "Av"},
                    {"AdTitleText", "Annonse!"},
                    {"AdBodyText", "Se annonsen for å fortsette å spille"},
                    {"TextYes", "Ja"},
                    {"TextNo", "Nei"},
                    {"LabelBack", "Angre"},
                    {"LabelErase", "Slett"},
                    {"LabelNotes", "Notatier"},
                    {"LabelHint", "Hint"},
                    {"LabelLaunguageConfirm", "BEKREFTE"},
                    {"GetHint", "Free x "},
                    { "BtnTextStatistic", "STATISTIKK"},
                    {"LabelGS", "Spill pabegynt:"},
                    {"LabelGW", "Spill vunnet:"},
                    {"LabelWR", "Seiersrate:"},
                    {"LabelWWM", "Seiere uten feil:"},
                    {"LabelBT", "Beste tid:"},
                    {"LabelAT", "Gjennomsnittlig tid:"},
                    {"LabelCWS", "Nåværende seiere på rad:"},
                    {"LabelBWS", "Høyest antall seiere på rad:"},
                    {"BtnReset", "Nullstill statistikk"},
                    {"ResetStatisticsText", "Statistikk for vanskelighetsgrad () vil bli slettet. Er du sikker?"},
                }); break;
                case "portuges": AddTranslations("portuges", new Dictionary<string, string>
                {// ç, ã, õ 
                    {"LabelContinue", "Continuar jogo"},
                    {"LabelNewGame", "Novo Jogo"},
                    {"LabelLevel1", "Fácil"},
                    {"LabelLevel2", "Médio"},
                    {"LabelLevel3", "Dificil"},
                    {"LabelLevel4", "Expert"},
                    {"LabelRestart", "Reinciar"},
                    {"LabelCancel", "Cancelar"},
                    {"LabelSettings", "CONFIGURAÇÕES"},
                    {"LabelDarkMode", "Modo escuro"},
                    {"LabelSounds", "Efeitos sonoros"},
                    {"LabelVibrations", "Vibrações"},
                    {"LabelTimer", "Temporizador"},
                    {"LabelMistakes", "Limite de erros"},
                    {"LabelAreas", "Áreas destacadas"},
                    {"LabelIdenticalNumber", "Destacar números idênticos"},
                    {"BtnTextRules", "COMO JOGAR"},
                    {"BtnTextLanguage", "TROCAR IDIOMA"},
                    {"BtnDiscard", "Pular"},
                    {"LabelTouchCell", "Toque nesta célula"},
                    {"LabelChooseNumber", "Selecione esse número"},
                    {"LabelAddNumber", "Isso pode ser preenchido com o número"},
                    {"LabelFinal", "Você já preencheu um quadrado, linha e coluna. O objetivo em Sudoku é fazer com que cada quadrado, linha e coluna contenha os números de 1 a 9."},
                    {"BtnFinal", "Toque para continuar"},
                    {"LabelGetTips", "Receba dicas"},
                    {"LabelSeeTips", "Assista ao anúncio para obter uma dica adicional."},
                    {"BtnSeeAd", "Assista ao anúncio"},
                    {"LabelMistake", "Erros" },
                    {"DisplayAlertFinalText", "Você resolveu o Sudoku com sucesso."},
                    {"LabelNotesOn", "Sim"},
                    {"LabelNotesOff", "Não"},
                    {"AdTitleText", "Anúncio!"},
                    {"AdBodyText", "Assista ao anúncio para continuar jogando"},
                    {"TextYes", "Sim"},
                    {"TextNo", "Não"},
                    {"LabelBack", "Desfazer"},
                    {"LabelErase", "Apagar"},
                    {"LabelNotes", "Notas"},
                    {"LabelHint", "Dicas"},
                    {"LabelLaunguageConfirm", "CONFIRMAR"},
                    {"GetHint", "Free x "},
                    { "BtnTextStatistic", "ESTATISTICAS"},
                    {"LabelGS", "Jogos iniciados:"},
                    {"LabelGW", "Vitórias em jogos:"},
                    {"LabelWR", "Taxa de vitórias:"},
                    {"LabelWWM", "Vitórias sem erros:"},
                    {"LabelBT", "Melhor tempo:"},
                    {"LabelAT", "Tempo médio:"},
                    {"LabelCWS", "Sequência atual de vitórias:"},
                    {"LabelBWS", "Melhor sequência de vitórias:"},
                    {"BtnReset", "Resetar estatísticas"},
                    {"ResetStatisticsText", "As estatísticas do nível () serão perididas. Tem certeza?"},
                }); break;
            }
        }

        // Metoda do dodawania tłumaczeń dla określonego języka
        public void AddTranslations(string language, Dictionary<string, string> translationsForLanguage)
        {
            if (!translations.TryAdd(language, translationsForLanguage))
            {
                // Jeśli tłumaczenia dla tego języka już istnieją, zastąp je nowymi
                translations[language] = translationsForLanguage;
            }
        }

        // Metoda do tłumaczenia tekstu na aktualnie wybrany język
        public string Translate(string language, string fieldName)
        {
            // Sprawdź, czy tłumaczenia dla danego języka istnieją
            if (translations.TryGetValue(language, out Dictionary<string, string> value))
            {
                var translationDictionary = value;

                // Sprawdź, czy pole o podanej nazwie istnieje w słowniku tłumaczeń
                if (translationDictionary.TryGetValue(fieldName, out string value1))
                {
                    // Zwróć tekst odpowiadający nazwie pola
                    return value1;
                }
            }
            // Jeśli tłumaczenie nie istnieje, zwróć oryginalny tekst
            return "";
        }

        // Metoda do ustawiania języka
        public void SetLanguage(string language)
        {
            // Ustaw nowy język w preferencjach
            Preferences.Set("CurrentLanguage", language);

            // Zaktualizuj domyślny język
            DefaultLanguage = language;
        }

        // Metoda do pobierania aktualnego języka
        public string GetLanguage()
        {
            return DefaultLanguage;
        }
    }
}
